import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#53555a",
        "surface-container-high": "#1d2025",
        "tertiary": "#ac8aff",
        "on-tertiary-fixed": "#1f0052",
        "on-surface": "#f6f6fc",
        "on-tertiary": "#280067",
        "secondary-dim": "#50ebd5",
        "on-tertiary-fixed-variant": "#4600a8",
        "surface-container-low": "#111318",
        "background": "#0c0e12",
        "surface": "#0c0e12",
        "inverse-surface": "#f9f9ff",
        "tertiary-dim": "#8455ef",
        "on-primary-fixed": "#004a2a",
        "surface-container-highest": "#23262c",
        "on-secondary-fixed": "#004840",
        "primary-fixed-dim": "#48f09c",
        "secondary-fixed": "#62fae3",
        "tertiary-container": "#8f60fa",
        "surface-container": "#171a1f",
        "secondary": "#62fae3",
        "primary-container": "#12d382",
        "error-dim": "#d7383b",
        "surface-tint": "#5affa9",
        "surface-variant": "#23262c",
        "on-tertiary-container": "#000000",
        "secondary-fixed-dim": "#50ebd5",
        "on-secondary-container": "#dcfff7",
        "secondary-container": "#006b5f",
        "primary": "#5affa9",
        "outline": "#74757a",
        "on-surface-variant": "#aaabb0",
        "surface-dim": "#0c0e12",
        "error": "#ff716c",
        "on-primary": "#005e37",
        "on-secondary": "#005c52",
        "primary-dim": "#48f09c",
        "on-error": "#490006",
        "tertiary-fixed": "#bda2ff",
        "primary-fixed": "#5affa9",
        "on-error-container": "#ffa8a3",
        "on-background": "#f6f6fc",
        "inverse-primary": "#006d41",
        "outline-variant": "#46484d",
        "surface-bright": "#292c33",
        "error-container": "#9f0519",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed-variant": "#00675c",
        "tertiary-fixed-dim": "#b091ff",
        "on-primary-fixed-variant": "#00693e",
        "on-primary-container": "#004024"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px"
      },
      backgroundImage: {
        "kinetic-gradient": "linear-gradient(135deg, #5affa9 0%, #62fae3 100%)",
      },
    },
  },
  plugins: [],
};
export default config;
